---
# file: roles/servers/tasks/ubuntu.yml
# Set the hostname and update /etc/hosts
- name: Change the hostname
  hostname: name="{{ inventory_hostname }}"
  become: yes

- name: Adjust /etc/hosts
  lineinfile: 
    state: present
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    regexp: "^{{ ansible_default_ipv4.address }}"

# Install Aptitude
- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest 
    update_cache: yes 
    force_apt_get: yes
  become: yes

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

# Update software
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: yes

# Update dist packages
- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: yes

# Install RPM
- name: Install rpm using apt
  apt: 
    name: rpm 
    state: latest 
    update_cache: yes 
    force_apt_get: yes
  become: yes

# Configure network interfaces
- name: configure udf interfaces
  template:
    src: netplan.j2
    dest: /etc/netplan/60-netcfg.yaml
    owner: root
    group: root
    mode: '0600'
  become: yes

# Apply the network configuration
- name: apply network configuration
  command: netplan apply
  become: yes